CREATE TABLE [dbo].[FactFlights]
(
	[Id] INT not null primary key,
	DepTime char(5), 
	DepTimeKey int, 
	CRSDepTime char(5), 
	CRSDepTimeKey int,
	ArrTime char(5),
	ArrTimeKey int ,
	CRSArrTime char(5),
	CRSArrTimeKey int,
	CarrierCodeKey int,
	PlaneKey int,
	OriginKey int,
	DestKey int,
	FlightNum smallint,
	ActualElapsedTime smallint,
	CRSElapsedTime smallint,
	AirTime smallint,
	ArrDelay smallint,
	DepDelay smallint,
	Distance real,
	TaxiIn smallint,
	TaxiOut smallint,
	Cancelled bit,
	CancellationCode char,
	Diverted bit,
	CarrierDelay smallint,
	WeatherDelay smallint,
	NASDelay smallint,
	SecurityDelay smallint,
	LateAircraftDelay smallint
)
